# Generated by Django 4.2.7 on 2023-11-29 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0011_remove_groupmessages_receiver_groups_groupcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='groupcode',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
