# Generated by Django 4.2.7 on 2023-11-30 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0007_videosale'),
    ]

    operations = [
        migrations.AddField(
            model_name='videosale',
            name='number',
            field=models.CharField(default=123, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videosale',
            name='ref',
            field=models.CharField(default='12w1', max_length=30),
            preserve_default=False,
        ),
    ]
